syntax = "proto3";
option csharp_namespace = "Sygnia.Presentation";
package users;

service UserService {
  rpc CreateUser(CreateUserRequest) returns (User);
  rpc GetUser(GetUserRequest) returns (User);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
}

message User {
  string id = 1;
  string name = 2;
  string surname = 3;
}

message CreateUserRequest {
  string id = 1;
  string name = 2;
  string surname = 3;
}

message GetUserRequest {
  string id = 1;
}

message ListUsersRequest {
}

message ListUsersResponse {
  repeated User users = 1;
}
