<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- Build properties are centralised in ..\Directory.Build.props -->
  <!-- Package versions are centralised in ..\Directory.Packages.props -->

  <ItemGroup>
    <Protobuf Include="Protos\movements.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\accounts.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\users.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sygnia.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Web" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sygnia.Application\Sygnia.Application.csproj" />
    <ProjectReference Include="..\Sygnia.Infrastructure\Sygnia.Infrastructure.csproj" />
  </ItemGroup>

</Project>
