/**
 * @fileoverview gRPC-Web generated client stub for accounts
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.15.6
// source: accounts.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as accounts_pb from './accounts_pb'; // proto import: "accounts.proto"


export class AccountServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateAccount = new grpcWeb.MethodDescriptor(
    '/accounts.AccountService/CreateAccount',
    grpcWeb.MethodType.UNARY,
    accounts_pb.CreateAccountRequest,
    accounts_pb.Account,
    (request: accounts_pb.CreateAccountRequest) => {
      return request.serializeBinary();
    },
    accounts_pb.Account.deserializeBinary
  );

  createAccount(
    request: accounts_pb.CreateAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<accounts_pb.Account>;

  createAccount(
    request: accounts_pb.CreateAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: accounts_pb.Account) => void): grpcWeb.ClientReadableStream<accounts_pb.Account>;

  createAccount(
    request: accounts_pb.CreateAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: accounts_pb.Account) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/accounts.AccountService/CreateAccount',
        request,
        metadata || {},
        this.methodDescriptorCreateAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/accounts.AccountService/CreateAccount',
    request,
    metadata || {},
    this.methodDescriptorCreateAccount);
  }

  methodDescriptorGetAccount = new grpcWeb.MethodDescriptor(
    '/accounts.AccountService/GetAccount',
    grpcWeb.MethodType.UNARY,
    accounts_pb.GetAccountRequest,
    accounts_pb.Account,
    (request: accounts_pb.GetAccountRequest) => {
      return request.serializeBinary();
    },
    accounts_pb.Account.deserializeBinary
  );

  getAccount(
    request: accounts_pb.GetAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<accounts_pb.Account>;

  getAccount(
    request: accounts_pb.GetAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: accounts_pb.Account) => void): grpcWeb.ClientReadableStream<accounts_pb.Account>;

  getAccount(
    request: accounts_pb.GetAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: accounts_pb.Account) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/accounts.AccountService/GetAccount',
        request,
        metadata || {},
        this.methodDescriptorGetAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/accounts.AccountService/GetAccount',
    request,
    metadata || {},
    this.methodDescriptorGetAccount);
  }

}

