/**
 * @fileoverview gRPC-Web generated client stub for movements
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.15.6
// source: movements.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as movements_pb from './movements_pb'; // proto import: "movements.proto"


export class MovementServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSubmitMovement = new grpcWeb.MethodDescriptor(
    '/movements.MovementService/SubmitMovement',
    grpcWeb.MethodType.UNARY,
    movements_pb.SubmitMovementRequest,
    movements_pb.Movement,
    (request: movements_pb.SubmitMovementRequest) => {
      return request.serializeBinary();
    },
    movements_pb.Movement.deserializeBinary
  );

  submitMovement(
    request: movements_pb.SubmitMovementRequest,
    metadata?: grpcWeb.Metadata | null): Promise<movements_pb.Movement>;

  submitMovement(
    request: movements_pb.SubmitMovementRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: movements_pb.Movement) => void): grpcWeb.ClientReadableStream<movements_pb.Movement>;

  submitMovement(
    request: movements_pb.SubmitMovementRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: movements_pb.Movement) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/movements.MovementService/SubmitMovement',
        request,
        metadata || {},
        this.methodDescriptorSubmitMovement,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/movements.MovementService/SubmitMovement',
    request,
    metadata || {},
    this.methodDescriptorSubmitMovement);
  }

  methodDescriptorTransfer = new grpcWeb.MethodDescriptor(
    '/movements.MovementService/Transfer',
    grpcWeb.MethodType.UNARY,
    movements_pb.TransferRequest,
    movements_pb.TransferResponse,
    (request: movements_pb.TransferRequest) => {
      return request.serializeBinary();
    },
    movements_pb.TransferResponse.deserializeBinary
  );

  transfer(
    request: movements_pb.TransferRequest,
    metadata?: grpcWeb.Metadata | null): Promise<movements_pb.TransferResponse>;

  transfer(
    request: movements_pb.TransferRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: movements_pb.TransferResponse) => void): grpcWeb.ClientReadableStream<movements_pb.TransferResponse>;

  transfer(
    request: movements_pb.TransferRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: movements_pb.TransferResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/movements.MovementService/Transfer',
        request,
        metadata || {},
        this.methodDescriptorTransfer,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/movements.MovementService/Transfer',
    request,
    metadata || {},
    this.methodDescriptorTransfer);
  }

  methodDescriptorGetBalance = new grpcWeb.MethodDescriptor(
    '/movements.MovementService/GetBalance',
    grpcWeb.MethodType.UNARY,
    movements_pb.GetBalanceRequest,
    movements_pb.GetBalanceResponse,
    (request: movements_pb.GetBalanceRequest) => {
      return request.serializeBinary();
    },
    movements_pb.GetBalanceResponse.deserializeBinary
  );

  getBalance(
    request: movements_pb.GetBalanceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<movements_pb.GetBalanceResponse>;

  getBalance(
    request: movements_pb.GetBalanceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: movements_pb.GetBalanceResponse) => void): grpcWeb.ClientReadableStream<movements_pb.GetBalanceResponse>;

  getBalance(
    request: movements_pb.GetBalanceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: movements_pb.GetBalanceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/movements.MovementService/GetBalance',
        request,
        metadata || {},
        this.methodDescriptorGetBalance,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/movements.MovementService/GetBalance',
    request,
    metadata || {},
    this.methodDescriptorGetBalance);
  }

  methodDescriptorGetStatement = new grpcWeb.MethodDescriptor(
    '/movements.MovementService/GetStatement',
    grpcWeb.MethodType.SERVER_STREAMING,
    movements_pb.GetStatementRequest,
    movements_pb.StatementLine,
    (request: movements_pb.GetStatementRequest) => {
      return request.serializeBinary();
    },
    movements_pb.StatementLine.deserializeBinary
  );

  getStatement(
    request: movements_pb.GetStatementRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<movements_pb.StatementLine> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/movements.MovementService/GetStatement',
      request,
      metadata || {},
      this.methodDescriptorGetStatement);
  }

  methodDescriptorGetStatementPage = new grpcWeb.MethodDescriptor(
    '/movements.MovementService/GetStatementPage',
    grpcWeb.MethodType.UNARY,
    movements_pb.GetStatementPageRequest,
    movements_pb.GetStatementPageResponse,
    (request: movements_pb.GetStatementPageRequest) => {
      return request.serializeBinary();
    },
    movements_pb.GetStatementPageResponse.deserializeBinary
  );

  getStatementPage(
    request: movements_pb.GetStatementPageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<movements_pb.GetStatementPageResponse>;

  getStatementPage(
    request: movements_pb.GetStatementPageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: movements_pb.GetStatementPageResponse) => void): grpcWeb.ClientReadableStream<movements_pb.GetStatementPageResponse>;

  getStatementPage(
    request: movements_pb.GetStatementPageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: movements_pb.GetStatementPageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/movements.MovementService/GetStatementPage',
        request,
        metadata || {},
        this.methodDescriptorGetStatementPage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/movements.MovementService/GetStatementPage',
    request,
    metadata || {},
    this.methodDescriptorGetStatementPage);
  }

}

