/**
 * @fileoverview gRPC-Web generated client stub for users
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.15.6
// source: users.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as users_pb from './users_pb'; // proto import: "users.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/users.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    users_pb.CreateUserRequest,
    users_pb.User,
    (request: users_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    users_pb.User.deserializeBinary
  );

  createUser(
    request: users_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<users_pb.User>;

  createUser(
    request: users_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: users_pb.User) => void): grpcWeb.ClientReadableStream<users_pb.User>;

  createUser(
    request: users_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: users_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/users.UserService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/users.UserService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/users.UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    users_pb.GetUserRequest,
    users_pb.User,
    (request: users_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    users_pb.User.deserializeBinary
  );

  getUser(
    request: users_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<users_pb.User>;

  getUser(
    request: users_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: users_pb.User) => void): grpcWeb.ClientReadableStream<users_pb.User>;

  getUser(
    request: users_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: users_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/users.UserService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/users.UserService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorListUsers = new grpcWeb.MethodDescriptor(
    '/users.UserService/ListUsers',
    grpcWeb.MethodType.UNARY,
    users_pb.ListUsersRequest,
    users_pb.ListUsersResponse,
    (request: users_pb.ListUsersRequest) => {
      return request.serializeBinary();
    },
    users_pb.ListUsersResponse.deserializeBinary
  );

  listUsers(
    request: users_pb.ListUsersRequest,
    metadata?: grpcWeb.Metadata | null): Promise<users_pb.ListUsersResponse>;

  listUsers(
    request: users_pb.ListUsersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: users_pb.ListUsersResponse) => void): grpcWeb.ClientReadableStream<users_pb.ListUsersResponse>;

  listUsers(
    request: users_pb.ListUsersRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: users_pb.ListUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/users.UserService/ListUsers',
        request,
        metadata || {},
        this.methodDescriptorListUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/users.UserService/ListUsers',
    request,
    metadata || {},
    this.methodDescriptorListUsers);
  }

}

