<Project Sdk="Microsoft.NET.Sdk">

  <!-- Build properties are centralised in ..\Directory.Build.props -->

  <ItemGroup>
    <InternalsVisibleTo Include="Sygnia.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sygnia.Application\Sygnia.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
